### ISSUE TITLE
FW_Shortcode_Widget_Area work if and only if page builder extension is active

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson#2081]
I have sidebar select option in theme options and page metabox. If page builder extension isn't active this error occurs 

```
Fatal error: Uncaught Error: Class 'FW_Shortcode_Widget_Area' not found in C:\xampp\htdocs\jane-love\wp-content\themes\janelove\framework\theme\options\janeloveoptions\post-options-meta.php:56 Stack trace: #0 C:\xampp\htdocs\jane-love\wp-content\plugins\unyson\framework\helpers\general.php(567): require() #1 C:\xampp\htdocs\jane-love\wp-content\plugins\unyson\framework\core\components\theme.php(80): fw_get_variables_from_file('C:\\xampp\\htdocs...', Array) #2 C:\xampp\htdocs\jane-love\wp-content\themes\janelove\framework\theme\options\posts\post.php(10): _FW_Component_Theme->get_options('janeloveoptions...') #3 C:\xampp\htdocs\jane-love\wp-content\plugins\unyson\framework\helpers\general.php(567): require('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\jane-love\wp-content\plugins\unyson\framework\core\components\theme.php(80): fw_get_variables_from_file('C:\\xampp\\htdocs...', Array) #5 C:\xampp\htdocs\jane-love\wp-content\plugins\unyson\framework\core\components\theme.php(122): _FW_Component_Theme->get_options('posts/post') in C:\xampp\htdocs\jane-love\wp-content\themes\janelove\framework\theme\options\janeloveoptions\post-options-meta.php on line 56
```

If the page builder extension is active there is no error. Shouldn't sidebar select is the core feature rather than depending on page builder extension?

**Comment by danyj** [comment]
theme is not checking for builder extension existence and is calling the builder FW_Shortcode_Widget_Area shortcode https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/tree/master/shortcodes/widget-area


theme\options\janeloveoptions\post-options-meta.php:56


that is a builder shortcode , not  this 

https://github.com/ThemeFuse/Unyson-Sidebars-Extension

**Comment by moldcraft** [comment]
The problem is in theme (not in Unyson)

```
\wp-content\themes\janelove\framework\theme\options\janeloveoptions\post-options-meta.php:56
```
