### ISSUE TITLE
Cannot Install Demo Content

### ISSUE THREAD

**Issue by Tamimal** [ThemeFuse/Unyson#3523]
When i'm trying to install demo from Demo Content Install page,
It's showing this error message 

" Failed to create tmp table _fwbk_wpdc_media_file_manager_log. You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci ROW_FORMAT=DYNAMIC' at line 3 "

**Comment by danyj** [comment]
what theme? did you update Unyson and backup extension to latest version ?

**Comment by ViorelEremia** [comment]
@Tamimal try this: https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/46883121b96d19e2f715092bc21e19be01d5140b
Or replace the file on your server ```wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php``` with [this](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php)

**Comment by kamleshpk** [comment]
I m using "Tradent Cryptocurrency - Bitcoin, Crypto Theme" same error. I tried above solution, but in vain.

**Comment by sylasfilho** [comment]
Hi,
Get into the file path wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/ and replace the class-fw-ext-backups-task-type-db-restore.php file using the below file .

File Path : https://www.dropbox.com/s/5mpt6tdt1tpumtp/class-fw-ext-backups-task-type-db-restore.php?dl=0

After that you can import the demo under the tools > demo install

**Comment by rexleonem** [comment]
> @Tamimal try this: [ThemeFuse/Unyson-Backups-Extension@4688312](https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/46883121b96d19e2f715092bc21e19be01d5140b)
> Or replace the file on your server `wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php` with [this](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php)

Thanks for sharing this 😊

**Comment by nobingit** [comment]
i am from bangladesh i have a theme that someone develop by unyson framework to install demo content. now i have changed my domain hosting so i cant install demo content now & my developer not helping me to resolve this, can you help me to full documentation or video tutorial to implement this, thanks in advance

**Comment by HillaryAW** [comment]
What can i do to solve this? I got this error message when I was about installing the demo

Uncaught ValueError: ZipArchive::setCompressionName(): Argument #1 ($name) cannot be empty in /code/wp-content/plugins/rainbowit-demo-importer-helper/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-zip.php:120 Stack trace: #0 /code/wp-content/plugins/rainbowit-demo-importer-helper/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-zip.php(120): ZipArchive->setCompressionName('', -1) #1 /code/wp-content/plugins/rainbowit-demo-importer-helper/unyson/framework/extensions/backups/includes/module/tasks/class--fw-ext-backups-module-tasks.php(579): FW_Ext_Backups_Task_Type_Zip->execute(Array, Array) #2 /code/wp-content/plugins/rainbowit-demo-importer-helper/unyson/framework/extensions/backups/includes/module/tasks/class--fw-ext-backups-module-tasks.php(743): _FW_Ext_Backups_Module_Tasks->execute_pending_task() #3 /code/wp-includes/class-wp-hook.php(324): _FW_Ext_Backups_Module_Tasks->_action_ajax_continue_pending_task('') #4 /code/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #5 /code/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #6 /code/wp-admin/admin-ajax.php(207): do_action('wp_ajax_nopriv_...') #7 {main} thrown in /code/wp-content/plugins/rainbowit-demo-importer-helper/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-zip.php on line 120
