### ISSUE TITLE
An error of type E_ERROR was caused in line 193 of the file

### ISSUE THREAD

**Issue by Worm78** [ThemeFuse/Unyson#3877]
I get this error whenever I try to edit a page that I created in Unyson...

Can anyone help me with fixing it please?

**When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.3
Current theme: eCoursify (version 1.0.0) Current plugin: Unyson (version 2.7.22) PHP version 7.1.33

Error Details
=============
An error of type E_ERROR was caused in line 193 of the file /home/worms/public_html/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php. Error message: Uncaught Error: Cannot unset string offsets in /home/worms/public_html/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php:193
Stack trace:
#0 /home/worms/public_html/wp-content/plugins/unyson/framework/core/extends/class-fw-option-type.php(281): FW_Option_Type->prepare('boxes', Array, Array)
#1 /home/worms/public_html/wp-content/plugins/unyson/framework/core/components/backend.php(1535): FW_Option_Type->enqueue_static('boxes', Array)
#2 /home/worms/public_html/wp-content/plugins/unyson/framework/helpers/general.php(1132): _FW_Component_Backend::_callback_fw_collect_options_enqueue_static(Array)
#3 /home/worms/public_html/wp-content/plugins/unyson/framework/helpers/general.php(1097): fw_collect_options(Array, Array, Array, Array)
#4 /home/worms/public_html/wp-content/plugins/unyson/framework/core/components/backend.php(1520): fw_collect_options(Array, Array, Array)
#5 /home/worms/public_html/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-b**

**Comment by Worm78** [comment]
Hello? Anyone?

**Comment by Worm78** [comment]
How do I get help?
