### ISSUE TITLE
Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by Bidibooum** [ThemeFuse/Unyson#4020]
Since today, i received this message on my website: critical error.
When i activated the debug, this is the message

Fatal error: Uncaught Error: Call to undefined function fw_ext_builder_get_item_width() in /customers/6/a/6/i-.com/httpd.www/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php:81 Stack trace: #0 /customers/6/a/6/i-.com/httpd.www/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/includes/items-corrector/class-page-builder-items-corrector.php(18): Page_Builder_Column_Item->get_value_from_attributes(Array) #1 /customers/6/a/6/i-.com/httpd.www/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/includes/page-builder/class-fw-option-type-page-builder.php(302): _Page_Builder_Items_Corrector->__construct(Array) #2 /customers/6/a/6/i-.com/httpd.www/wp-content/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/class-fw-extension-page-builder.php(391): FW_Option_Type_Page_Builder->json_to_shortcodes(Array) #3 /custome in /customers/6/a/6/i-.com/httpd.www/wp-content/plugins/unyson/framework/extensions/shortcodes/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php on line 81

How to fix it?

**Comment by Ruslan2205** [comment]
I'm not sure, but it looks very much like the page is not built correctly. Try switching to text mode, save a copy of the content, clear the page content. If the error disappears, then there is clearly an error in the page content. If it is not possible to enter the control panel, then you need to clear the data in the database.

**Comment by Bidibooum** [comment]
it's stronge because beofre I never have this message, and my page still the same.

I also received this mail:

Une erreur de type E_COMPILE_ERROR a été causée dans la ligne 353 du fichier /customers/6/a/6/i-.com/httpd.www/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/extends/class-fw-option-type-builder.php. Message d’erreur : Array and string offset access syntax with curly braces is no longer supported

**Comment by Ruslan2205** [comment]
Have you changed php version?

**Comment by Bidibooum** [comment]
I think my hoster change to php 7.4 yes.

**Comment by Ruslan2205** [comment]
Then maybe that's the problem. Now either you need to go back to the old version, or rewrite the deprecated functions.

**Comment by Bidibooum** [comment]
Ok, i will be check to rollback to 7.3

Thank you
