### ISSUE TITLE
The Editor Has Encountered An Unexpected Error

### ISSUE THREAD

**Issue by grimesdiscounts** [ThemeFuse/Unyson#4031]
Hello, 

My editor thingy is broken, I cannot edit pages or posts... How do fix this? Please help me out. I've been googling since last night.

I'm on WordPress 5.5 and trying to edit already existing pages and posts using Unyson...when I press EDIT on any pages and posts I receive this white box with the error. 

I've restored from backup 3 times, I've updated all plugins... It was working fine 2 days ago... My theme is CouponHut but I've changed to 2 different themes and still get this error.

😞😞😞 <== sad faces for empathy!

Here is a photo of what it looks like --- ![image](https://user-images.githubusercontent.com/69605358/90068323-5448e780-dca5-11ea-8a3c-1501e2af80f0.png)

ReferenceError: YoastSEO is not defined
    at i (https://grimesdealsanddiscounts.com/wp-content/plugins/wordpress-seo/js/dist/post-edit-1470.js:1:2331)
    at t.default (https://grimesdealsanddiscounts.com/wp-content/plugins/wordpress-seo/js/dist/post-edit-1470.js:1:2169)
    at t.value (https://grimesdealsanddiscounts.com/wp-content/plugins/wordpress-seo/js/dist/post-edit-1470.js:1:54110)
    at re (https://grimesdealsanddiscounts.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:95:261)
    at Vg (https://grimesdealsanddiscounts.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:95:54)
    at ph (https://grimesdealsanddiscounts.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:217:70)
    at lh (https://grimesdealsanddiscounts.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:126:409)
    at O (https://grimesdealsanddiscounts.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:121:71)
    at ze (https://grimesdealsanddiscounts.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:118:14)
    at https://grimesdealsanddiscounts.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:53:49

I have since deactivated the Yoast plugin after copying the error code from the page above and still do not see the Unyson page builder this is what I see below. 

![image](https://user-images.githubusercontent.com/69605358/90069689-81969500-dca7-11ea-8486-b84bf54376a4.png)

Please help this is VERY frustrating because I was already having trouble building this website with the awful page builder.

Thanks,

Charel

**Comment by j-Kode** [comment]
Im having the same problem :(

**Comment by j-Kode** [comment]
@grimesdiscounts Just figured it out. I think Unyson Builder has a bug with 5.5 so if you go to your wordpress backend -> Dashboard -> Updates there should be an area saying 
`You have the latest version of WordPress.
If you need to re-install version 5.4.2, you can do so here:`

Click the link and continue, if you don't see that message then download **WP Downgrade** plugin and backup your wordpress install and db. Once done backing up revert to a version you want, I can confirm that the page builder works on 5.4.2. Hope this helps. 👍

**Comment by grimesdiscounts** [comment]
@j-Kode I have noooooo idea who you are BUT I THANK YOU SO MUCH, this worked!! BIG HUGS MY VIRTUAL WEBSITE SAVIOR!!!!!! <3 <3 <3

**Comment by j-Kode** [comment]
@grimesdiscounts no prob, sucks when your website is not working. Glad I could help
