### ISSUE TITLE
Uncaught fatal error in session_id()

### ISSUE THREAD

**Issue by nascimentoraony** [ThemeFuse/Unyson#4126]
I'm using Wordpress and Unyson for the first time, and i'm facin a trouble that I don't know how to solve. 
When unyson is activated wordpress stops to function, if the plugin is deactivated everything works fine.

The error i'm getting is this:

Fatal error: Uncaught Error: Call to undefined function session_id() in /usr/local/www/nginx-dist/wp-content/plugins/unyson/framework/includes/hooks.php:228 Stack trace: #0 /usr/local/www/nginx-dist/wp-includes/class-wp-hook.php(292): _action_fw_flash_message_backend_prepare() #1 /usr/local/www/nginx-dist/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters() #2 /usr/local/www/nginx-dist/wp-includes/plugin.php(484): WP_Hook->do_action() #3 /usr/local/www/nginx-dist/wp-admin/includes/class-wp-screen.php(421): do_action() #4 /usr/local/www/nginx-dist/wp-admin/includes/screen.php(240): WP_Screen->set_current_screen() #5 /usr/local/www/nginx-dist/wp-admin/admin.php(212): set_current_screen() #6 /usr/local/www/nginx-dist/wp-admin/index.php(10): require_once('/usr/local/www/...') #7 {main} thrown in /usr/local/www/nginx-dist/wp-content/plugins/unyson/framework/includes/hooks.php on line 228

I already looked at pull requests and updated hook.php and class-fw-session.php, cause they seemed to be the source of my problem, but the error persists.

(Sorry, for my poor english.)

Thanks for any help.

**Comment by nascimentoraony** [comment]
More information:
OS: 12.2-RC1
NGINX: nginx/1.18.0
PHP: PHP 7.4.15 (cli) (built: Feb  9 2021 01:16:54) ( NTS )
Mysql: Ver 8.0.23 for FreeBSD12.2 on amd64 (Source distribution)
